//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long comentarioId { get; set; }
        public long ImagenSetId { get; set; }
        public long UserProfile_usrId { get; set; }
        public string Texto { get; set; }
        public System.DateTime Date { get; set; }
        public string author { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): ComentarioImagenSet
        /// </summary>
        public virtual ImageSet ImagenSet { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): ComentarioUserProfile
        /// </summary>
        public virtual UserProfile UserProfile { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	/*public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + ImagenSetId.GetHashCode();
    			hash = hash * multiplier + UserProfile_usrId.GetHashCode();
    			hash = hash * multiplier + (Texto == null ? 0 : Texto.GetHashCode());
    			hash = hash * multiplier + Date.GetHashCode();
    			hash = hash * multiplier + (author == null ? 0 : author.GetHashCode());
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type?
    	    
            Comment target = obj as Comment;
    
    		return true
               &&  (this.comentarioId == target.comentarioId )       
               &&  (this.ImagenSetId == target.ImagenSetId )       
               &&  (this.UserProfile_usrId == target.UserProfile_usrId )       
               &&  (this.Texto == target.Texto )       
               &&  (this.Date == target.Date )       
               &&  (this.author == target.author )       
               ;
    
        }*/
    
    
    	public static bool operator ==(Comment  objA, Comment  objB)
        {
            // Check if the objets are the same Comment entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Comment  objA, Comment  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strComment = new StringBuilder();
    
    		strComment.Append("[ ");
           strComment.Append(" comentarioId = " + comentarioId + " | " );       
           strComment.Append(" ImagenSetId = " + ImagenSetId + " | " );       
           strComment.Append(" UserProfile_usrId = " + UserProfile_usrId + " | " );       
           strComment.Append(" Texto = " + Texto + " | " );       
           strComment.Append(" Date = " + Date + " | " );       
           strComment.Append(" author = " + author + " | " );       
            strComment.Append("] ");    
    
    		return strComment.ToString();
        }
    
    
    }
}
