//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class EXIF
    {
        public EXIF()
        {
            this.ImageSet = new HashSet<ImageSet>();
        }
    
        public long Id { get; set; }
        public string Apertura { get; set; }
        public string TExposicion { get; set; }
        public string ISO { get; set; }
        public string WB { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): EXIFImageSet
        /// </summary>
        public virtual ICollection<ImageSet> ImageSet { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + (Apertura == null ? 0 : Apertura.GetHashCode());
    			hash = hash * multiplier + (TExposicion == null ? 0 : TExposicion.GetHashCode());
    			hash = hash * multiplier + (ISO == null ? 0 : ISO.GetHashCode());
    			hash = hash * multiplier + (WB == null ? 0 : WB.GetHashCode());
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type?
    	    
            EXIF target = obj as EXIF;
    
    		return true
               &&  (this.Id == target.Id )       
               &&  (this.Apertura == target.Apertura )       
               &&  (this.TExposicion == target.TExposicion )       
               &&  (this.ISO == target.ISO )       
               &&  (this.WB == target.WB )       
               ;
    
        }
    
    
    	public static bool operator ==(EXIF  objA, EXIF  objB)
        {
            // Check if the objets are the same EXIF entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(EXIF  objA, EXIF  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strEXIF = new StringBuilder();
    
    		strEXIF.Append("[ ");
           strEXIF.Append(" Id = " + Id + " | " );       
           strEXIF.Append(" Apertura = " + Apertura + " | " );       
           strEXIF.Append(" TExposicion = " + TExposicion + " | " );       
           strEXIF.Append(" ISO = " + ISO + " | " );       
           strEXIF.Append(" WB = " + WB + " | " );       
            strEXIF.Append("] ");    
    
    		return strEXIF.ToString();
        }
    
    
    }
}
