//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PracticaMaDEntities : DbContext
    {
        public PracticaMaDEntities()
            : base("name=PracticaMaDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImageSet> ImagenSet { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<Category> CategorySet { get; set; }
        public virtual DbSet<Comment> CommentSet { get; set; }
        public virtual DbSet<EXIF> EXIFSet { get; set; }
        public virtual DbSet<Tag> TagSet { get; set; }
    }
}
